autonomy: 6
departure: "Tatooine"
arrival: "Endor"
routes_db: db/universe.db

spring:
  datasource:
    url: jdbc:sqlite:${routes_db}
    driver-class-name: org.sqlite.JDBC
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-missing-creator-properties: true